import os
import random
import importlib
import threading
import shutil
import pygame

import app.coder as coder
import app.narrator as narrator

from utils.utils import clean_ai_code
from utils.constants import (
    GAME_LOGIC_PATH,
    GAME_LOGIC_BACKUP_PATH,
    GAME_LOGIC_ORIGINAL_PATH,
)

import game.game_logic as game_logic  # vibe file
from game.constants import GlobalRegistry

# initialize original backup if not exists
if not os.path.exists(GAME_LOGIC_ORIGINAL_PATH):
    shutil.copy(GAME_LOGIC_PATH, GAME_LOGIC_ORIGINAL_PATH)
    print(f"Created base backup: {GAME_LOGIC_ORIGINAL_PATH}")

pygame.init()
screen = pygame.display.set_mode((800, 600))
clock = pygame.time.Clock()

# constant game registry that survives hot reloads
registry = GlobalRegistry()


def get_streaming_vibe(user_intent, current_code, screen):
    """
    Interleaves LLM streaming with Pygame rendering to prevent freezing.
    """
    stream_response = coder.get_code_stream(user_intent, current_code, screen)

    registry.time_dilation = 0.2

    full_content = ""
    for chunk in stream_response:

        if len(full_content) % 500 == 0:
            threading.Thread(
                target=narrator.announce_vibe_shift,
                args=("Hold steady, Brawler. The arena is shifting.",),
            ).start()

        token = chunk.data.choices[0].delta.content
        if token:
            full_content += token

            screen.fill((20, 20, 20))
            game_logic.update(screen, registry)

            font = pygame.font.SysFont("Arial", 24, bold=True)
            txt = font.render(
                f"REALITY RECONSTRUCTING: {len(full_content)} BYTES",
                True,
                (255, 200, 0),
            )
            screen.blit(txt, (400 - txt.get_width() // 2, 50))

            render_offset = (random.randint(-5, 5), random.randint(-5, 5))
            screen.blit(screen, render_offset)

            pygame.display.flip()
            pygame.event.pump()

    registry.time_dilation = 1.0

    return full_content


def apply_new_vibe(raw_ai_message):
    """
    Validates and applies the new game logic code generated by the AI.
    If the code is invalid, it reverts to the last known good state.
    """
    clean_code = clean_ai_code(raw_ai_message)

    try:
        compile(clean_code, GAME_LOGIC_PATH, "exec")
    except Exception as e:
        print(f"BRAWL ERROR: AI generated invalid syntax: {e}")
        narrator.architect_commentary("glitch")
        return False

    with open(GAME_LOGIC_BACKUP_PATH, "w") as b:
        with open(GAME_LOGIC_PATH, "r") as f:
            b.write(f.read())

    with open(GAME_LOGIC_PATH, "w") as f:
        f.write(clean_code)

    try:
        importlib.reload(game_logic)
        print(f"Vibe Shifted!")
        return True
    except Exception as e:
        print(f"Runtime Error during reload: {e}")
        narrator.architect_commentary("glitch")
        os.replace(GAME_LOGIC_BACKUP_PATH, GAME_LOGIC_PATH)
        return False


if __name__ == "__main__":
    # narrator.architect_commentary("intro")

    running = True
    while running:
        for event in pygame.event.get():
            # quit game
            if event.type == pygame.QUIT:
                running = False

            # Scroll log
            if event.type == pygame.MOUSEBUTTONDOWN:
                if event.button == 4:  # Scroll Up
                    registry.log_scroll += 1
                elif event.button == 5:  # Scroll Down
                    registry.log_scroll -= 1

            # get user command via voice - TOGGLE MODE
            if event.type == pygame.KEYDOWN and event.key == pygame.K_SPACE:
                if not registry.game_started:
                    continue

                if not registry.is_recording:
                    # START RECORDING
                    if registry.player.mana < 10:
                        registry.combat_log.append(
                            "Architect: Your mana is too low to shift reality."
                        )
                        narrator.announce_vibe_shift("Mana depleted, Brawler.")
                        continue

                    registry.is_recording = True
                    registry.player.mana -= 10
                    registry.combat_log.append(
                        "Architect: LISTENING... (Press Space again to finish)"
                    )
                    narrator.start_recording()
                else:
                    # STOP AND PROCESS
                    registry.is_recording = False
                    user_command = (narrator.stop_and_transcribe() or "").lower()

                    if user_command:
                        registry.screen_shake = 60  # Start shake

                        # 1. Special Quest Command: Pulse of Truth
                        is_special = False
                        for word in ["pulse", "truth", "reveal"]:
                            if word in user_command:
                                registry.hidden_sigil_revealed = True
                                registry.combat_log.append(
                                    "Architect: REALITY PULSING... The hidden is revealed."
                                )
                                narrator.announce_vibe_shift(
                                    "The veil is thin, Brawler."
                                )
                                is_special = True
                                break
                        if is_special:
                            continue

                        # 2. Boss Phase Spells
                        if registry.lillith_barrier_strength <= 0:
                            spell_type = "arcane"
                            color = (100, 100, 255)
                            if "lightning" in user_command or "bolt" in user_command:
                                spell_type, color = "lightning", (255, 255, 0)
                            elif "ice" in user_command or "freeze" in user_command:
                                spell_type, color = "ice", (100, 255, 255)
                            elif "fire" in user_command or "burn" in user_command:
                                spell_type, color = "fire", (255, 100, 0)

                            dx, dy = (
                                registry.villain.x - registry.player.x,
                                registry.villain.y - registry.player.y,
                            )
                            n = max(1, (dx**2 + dy**2) ** 0.5)
                            registry.player.spells.append(
                                {
                                    "x": registry.player.x,
                                    "y": registry.player.y,
                                    "vx": (dx / n) * 8,
                                    "vy": (dy / n) * 8,
                                    "color": color,
                                    "size": 15,
                                    "life": 120,
                                    "type": spell_type,
                                }
                            )
                            registry.combat_log.append(
                                f"Architect: CASTING {spell_type.upper()}!"
                            )
                            narrator.announce_vibe_shift(f"Feel the {spell_type}!")
                            continue

                        # 3. Regular Vibe Shift
                        with open(GAME_LOGIC_PATH, "r") as f:
                            current_code = f.read()

                        raw_new_code = get_streaming_vibe(
                            user_command, current_code, screen
                        )
                        success = apply_new_vibe(raw_new_code)

                        if success:
                            registry.combat_log.append(
                                f"Architect: Shifted {user_command}."
                            )
                        else:
                            registry.combat_log.append(
                                "Architect: Reality reject. Glitch detected."
                            )

                        threading.Thread(
                            target=narrator.announce_vibe_shift,
                            args=("Reality stabilized.",),
                        ).start()

        # 4. Check for logic reset
        if registry.needs_reload:
            registry.needs_reload = False
            print("Restoring original game logic...")
            shutil.copy(GAME_LOGIC_ORIGINAL_PATH, GAME_LOGIC_PATH)
            importlib.reload(game_logic)
            registry.combat_log.append("Architect: REALITY RESTORED TO BASELINE.")

        # regular game update
        # logic handles player movement, map rendering, and NPCs
        game_logic.update(screen, registry)

        pygame.display.flip()
        clock.tick(60)
